// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Credenciais do NOVO projeto Supabase (izhbmjqyoglagooosmoc)
const SUPABASE_URL = "https://izhbmjqyoglagooosmoc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml6aGJtanF5b2dsYWdvb29zbW9jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMwNjQxNjQsImV4cCI6MjA4ODY0MDE2NH0.dtxoOsaAn0sNMDbLcfpljAmI-he5WDuAe7Vk6gZcKmI";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});